# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starId', models.IntegerField(default=0)),
                ('albumId', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50, null=True)),
                ('cover', models.CharField(max_length=100, null=True)),
                ('imageListFile', models.CharField(max_length=100, null=True)),
                ('pictureCnt', models.IntegerField(default=0, null=True)),
                ('publishDate', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(null=True)),
                ('company', models.CharField(max_length=50, null=True)),
                ('tag', models.CharField(default='', max_length=50, null=True)),
                ('termId', models.PositiveIntegerField(null=True)),
                ('lastModified', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starId', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.CharField(max_length=20, null=True)),
                ('cover', models.URLField(default=None, null=True)),
                ('threeD', models.CharField(max_length=15, null=True)),
                ('height', models.IntegerField(default=None, null=True)),
                ('weight', models.FloatField(default=None, null=True)),
                ('hobby', models.CharField(max_length=40, null=True)),
                ('birthPlace', models.CharField(default='', max_length=15, null=True)),
                ('description', models.CharField(default='', max_length=500, null=True)),
                ('tag', models.CharField(default='', max_length=500, null=True)),
                ('work', models.CharField(default='', max_length=50, null=True)),
                ('lastModified', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(default='', max_length=25)),
                ('tagId', models.CharField(default='', max_length=20)),
                ('tagTypeName', models.CharField(max_length=50, null=True)),
                ('tagTypeId', models.CharField(default='', max_length=20)),
                ('IdList', models.CharField(max_length=10000, null=True)),
            ],
        ),
    ]
