# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 10:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='lastModified',
            field=models.DateField(default=datetime.datetime(2017, 11, 29, 10, 49, 9, 173476)),
        ),
    ]
