# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_youwu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=15)),
                ('tagID', models.IntegerField()),
                ('tagTypeName', models.CharField(max_length=50)),
                ('tagTypeID', models.IntegerField()),
                ('albumID', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='star',
            name='lastModified',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='album',
            name='publishDate',
            field=models.CharField(max_length=15),
        ),
    ]
