# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_youwu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='albumID',
            new_name='albumId',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='tagID',
            new_name='tagId',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='tagTypeID',
            new_name='tagTypeId',
        ),
    ]
