# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_youwu', '0002_star_lastmodified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='publishDate',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='star',
            name='lastModified',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
