# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_youwu', '0002_auto_20171211_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tag',
            new_name='tags',
        ),
    ]
