def get_tags():
    company_type = [
        {"tagName": "爱尤物", "tagId": "aiyouwu", "tagTypeId": "Album"},
        {"tagName": "尤果网", "tagId": "ugirl", "tagTypeId": "Album"},
        {"tagName": "尤物馆", "tagId": "youwuguan", "tagTypeId": "Album"},
        {"tagName": "尤蜜荟", "tagId": "youmihui", "tagTypeId": "Album"},
        {"tagName": "蜜桃社", "tagId": "miitao", "tagTypeId": "Album"},
        {"tagName": "爱蜜社", "tagId": "imiss", "tagTypeId": "Album"},
        {"tagName": "优星馆", "tagId": "uxing", "tagTypeId": "Album"},
        {"tagName": "魅妍社", "tagId": "mistar", "tagTypeId": "Album"},
        {"tagName": "波萝社", "tagId": "bololi", "tagTypeId": "Album"},
        {"tagName": "优果网", "tagId": "youguo", "tagTypeId": "Album"},
        {"tagName": "青豆客", "tagId": "qingdouke", "tagTypeId": "Album"},
        {"tagName": "秀人网", "tagId": "xiuren", "tagTypeId": "Album"},
        {"tagName": "推女神", "tagId": "tgod", "tagTypeId": "Album"},
        {"tagName": "美媛馆", "tagId": "meiyuanguan", "tagTypeId": "Album"},
        {"tagName": "推女郎", "tagId": "tuigirl", "tagTypeId": "Album"},
        {"tagName": "兔几盟", "tagId": "tukmo", "tagTypeId": "Album"},
        {"tagName": "激萌文化", "tagId": "kimoe", "tagTypeId": "Album"},
        {"tagName": "花漾", "tagId": "huayan", "tagTypeId": "Album"},
        {"tagName": "影私荟", "tagId": "wings", "tagTypeId": "Album"},
        {"tagName": "克拉女神", "tagId": "kela", "tagTypeId": "Album"},
        {"tagName": "星颜社", "tagId": "xingyan", "tagTypeId": "Album"},
        {"tagName": "花漾", "tagId": "huayang", "tagTypeId": "Album"},
        {"tagName": "猫萌榜", "tagId": "micat", "tagTypeId": "Album"},
        {"tagName": "果团网", "tagId": "girlt", "tagTypeId": "Album"},
        {"tagName": "51modo", "tagId": "51modo", "tagTypeId": "Album"},
        {"tagName": "薄荷叶", "tagId": "mintye", "tagTypeId": "Album"},
        {"tagName": "糖果画报", "tagId": "candy", "tagTypeId": "Album"},
        {"tagName": "飞图网", "tagId": "ftoow", "tagTypeId": "Album"},
        {"tagName": "星乐园", "tagId": "leyuan", "tagTypeId": "Album"},
        {"tagName": "顽味生活", "tagId": "taste", "tagTypeId": "Album"},
        {"tagName": "御女郎", "tagId": "yunvlang", "tagTypeId": "Album"},
        {"tagName": "嗲囡囡", "tagId": "feilin", "tagTypeId": "Album"},
        {"tagName": "模范学院", "tagId": "mfstar", "tagTypeId": "Album"},
        {"tagName": "头条女神", "tagId": "toutiao", "tagTypeId": "Album"},
    ]

    body_type = [
        {"tagName": "人间胸器", "tagId": "xiongqi", "tagTypeId": "Album"},
        {"tagName": "波涛胸涌", "tagId": "botao", "tagTypeId": "Album"},
        {"tagName": "美臀", "tagId": "meitun", "tagTypeId": "Album"},
        {"tagName": "尤物", "tagId": "youwu", "tagTypeId": "Album"},
        {"tagName": "玉足", "tagId": "yuzu", "tagTypeId": "Album"},
        {"tagName": "香肩", "tagId": "xiangjian", "tagTypeId": "Album"},
        {"tagName": "蜜桃臀", "tagId": "mitaotun", "tagTypeId": "Album"},
        {"tagName": "小麦色", "tagId": "xiaomaise", "tagTypeId": "Album"},
        {"tagName": "白嫩", "tagId": "bainen", "tagTypeId": "Album"},
        {"tagName": "肉感", "tagId": "rougan", "tagTypeId": "Album"},
        {"tagName": "童颜巨乳", "tagId": "tongyanjuru", "tagTypeId": "Album"},
        {"tagName": "美腿", "tagId": "meitui", "tagTypeId": "Album"},
        {"tagName": "大尺度", "tagId": "dachidu", "tagTypeId": "Album"},
    ]

    person_feature_type = [
        {"tagName": "极品", "tagId": "jipin", "tagTypeId": "Album"},
        {"tagName": "女神", "tagId": "nvshen", "tagTypeId": "Album"},
        {"tagName": "混血", "tagId": "hunxue", "tagTypeId": "Album"},
        {"tagName": "野性", "tagId": "yexing", "tagTypeId": "Album"},
        {"tagName": "性感", "tagId": "xinggan", "tagTypeId": "Album"},
        {"tagName": "冷艳", "tagId": "lengyan", "tagTypeId": "Album"},
        {"tagName": "气质", "tagId": "qizhi", "tagTypeId": "Album"},
        {"tagName": "治愈系", "tagId": "zhiyu", "tagTypeId": "Album"},
        {"tagName": "清新", "tagId": "qingxin", "tagTypeId": "Album"},
        {"tagName": "清纯", "tagId": "qingchun", "tagTypeId": "Album"},
        {"tagName": "诱惑", "tagId": "youhuo", "tagTypeId": "Album"},
        {"tagName": "娇小萝莉", "tagId": "jiaoxiao", "tagTypeId": "Album"},
        {"tagName": "骨感", "tagId": "gugan", "tagTypeId": "Album"},
        {"tagName": "养眼", "tagId": "yangyan", "tagTypeId": "Album"},
        {"tagName": "萌系", "tagId": "mengxi", "tagTypeId": "Album"},
        {"tagName": "妩媚", "tagId": "wumei", "tagTypeId": "Album"},
        {"tagName": "萝莉", "tagId": "luoli", "tagTypeId": "Album"},
        {"tagName": "姐妹花", "tagId": "jiemeihua", "tagTypeId": "Album"}
    ]

    clothes_type = [
        {"tagName": "湿身", "tagId": "shishen", "tagTypeId": "Album"},
        {"tagName": "比基尼", "tagId": "bijini", "tagTypeId": "Album"},
        {"tagName": "制服", "tagId": "zhifu", "tagTypeId": "Album"},
        {"tagName": "校服", "tagId": "xiaofu", "tagTypeId": "Album"},
        {"tagName": "护士", "tagId": "hushi", "tagTypeId": "Album"},
        {"tagName": "角色扮演", "tagId": "cos", "tagTypeId": "Album"},
        {"tagName": "内衣", "tagId": "neiyi", "tagTypeId": "Album"},
        {"tagName": "女仆", "tagId": "nvpu", "tagTypeId": "Album"},
        {"tagName": "黑丝", "tagId": "heisi", "tagTypeId": "Album"},
        {"tagName": "和服", "tagId": "hefu", "tagTypeId": "Album"},
        {"tagName": "丁字裤", "tagId": "dingziku", "tagTypeId": "Album"},
        {"tagName": "空姐", "tagId": "kongjie", "tagTypeId": "Album"},
        {"tagName": "旗袍", "tagId": "qipao", "tagTypeId": "Album"},
        {"tagName": "肚兜", "tagId": "dudou", "tagTypeId": "Album"},
        {"tagName": "开背毛衣", "tagId": "kaibei", "tagTypeId": "Album"},
        {"tagName": "拳击宝贝", "tagId": "quanji", "tagTypeId": "Album"},
        {"tagName": "篮球宝贝", "tagId": "lanqiu", "tagTypeId": "Album"},
        {"tagName": "足球宝贝", "tagId": "zuqiu", "tagTypeId": "Album"},
    ]

    place_type = [
        {"tagName": "户外", "tagId": "huwai", "tagTypeId": "Album"},
        {"tagName": "家居", "tagId": "jiaju", "tagTypeId": "Album"},
        {"tagName": "街拍", "tagId": "jiepai", "tagTypeId": "Album"},
        {"tagName": "私房照", "tagId": "sifang", "tagTypeId": "Album"},
        {"tagName": "沙漠", "tagId": "shamo", "tagTypeId": "Album"},
        {"tagName": "春节", "tagId": "chunjie", "tagTypeId": "Album"},
        {"tagName": "圣诞", "tagId": "christmas", "tagTypeId": "Album"},
        {"tagName": "浴室", "tagId": "yushi", "tagTypeId": "Album"},
        {"tagName": "泳池", "tagId": "yongchi", "tagTypeId": "Album"},
        {"tagName": "沙滩", "tagId": "shatan", "tagTypeId": "Album"},
    ]

    country_type = [
        {"tagName": "菲律宾", "tagId": "feilvbin", "tagTypeId": "Album"},
        {"tagName": "泰国", "tagId": "taiguo", "tagTypeId": "Album"},
        {"tagName": "越南", "tagId": "yuenan", "tagTypeId": "Album"},
        {"tagName": "马来西亚", "tagId": "malaixiya", "tagTypeId": "Album"},
        {"tagName": "韩国", "tagId": "hanguo", "tagTypeId": "Album"},
        {"tagName": "日本少女", "tagId": "riben", "tagTypeId": "Album"},
        {"tagName": "澳门", "tagId": "aomen", "tagTypeId": "Album"},
        {"tagName": "香港", "tagId": "xianggang", "tagTypeId": "Album"},
        {"tagName": "台湾", "tagId": "taiwan", "tagTypeId": "Album"},
        {"tagName": "乌克兰", "tagId": "wukelan", "tagTypeId": "Album"},
        {"tagName": "俄罗斯", "tagId": "eluosi", "tagTypeId": "Album"},
        {"tagName": "日韩", "tagId": "rihan", "tagTypeId": "Album"},
        {"tagName": "意大利", "tagId": "yidali", "tagTypeId": "Album"},
        {"tagName": "德国", "tagId": "deguo", "tagTypeId": "Album"},
        {"tagName": "法国", "tagId": "faguo", "tagTypeId": "Album"},
        {"tagName": "英国", "tagId": "yingguo", "tagTypeId": "Album"},
        {"tagName": "美国", "tagId": "meiguo", "tagTypeId": "Album"},
        {"tagName": "印度", "tagId": "yindu", "tagTypeId": "Album"},
    ]

    other_company_type = [
        {"tagName": "Sabra.net", "tagId": "sabra", "tagTypeId": "Album"},
        {"tagName": "@misty", "tagId": "misty", "tagTypeId": "Album"},
        {"tagName": "Bomb.tv", "tagId": "bomb", "tagTypeId": "Album"},
        {"tagName": "DGC套图", "tagId": "dgcc", "tagTypeId": "Album"},
        {"tagName": "beautyleg", "tagId": "beautyleg", "tagTypeId": "Album"},
        {"tagName": "Weekly Young Jump", "tagId": "jump", "tagTypeId": "Album"},
        {"tagName": "Young Magazine", "tagId": "young", "tagTypeId": "Album"},
        {"tagName": "Weekly Playboy", "tagId": "playboy", "tagTypeId": "Album"},
        {"tagName": "Young Champion", "tagId": "champion", "tagTypeId": "Album"},
        {"tagName": "Weekly Big Comic Spirits", "tagId": "bigcomic", "tagTypeId": "Album"},
        {"tagName": "体育画报", "tagId": "sportillustrated", "tagTypeId": "Album"},
    ]
    return [company_type, body_type, person_feature_type, place_type,country_type ,other_company_type ]
